say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . horse_revive . _50_say ) 
wait ( ) 
say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . horse_revive . _60_say ) 
horse . summon ( ) 
wait ( ) 
say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . horse_revive . _70_say ) 
if pc . countitem ( "50059" ) >= 1 then 
pc . removeitem ( "50059" , 1 ) 
horse . revive ( ) 
end 
