say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . horse_revive . _20_say ) 
if pc . countitem ( "50058" ) >= 1 then 
say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . horse_revive . _30_say ) 
elseif pc . countitem ( "50057" ) >= 1 then 
say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . horse_revive . _40_say ) 
end 
