if pc . getqf ( "open_item_storage_count" ) < 3 then 
say_title ( gameforge . subquest_26 . _30_sayTitle ) 
say ( gameforge . warehouse . _140_say ) 
wait ( ) 
say_title ( gameforge . subquest_26 . _30_sayTitle ) 
say_show_item ( 90013 ) 
say ( gameforge . warehouse . _150_say ) 
wait ( ) 
pc . setqf ( "open_item_storage_count" , pc . getqf ( "open_item_storage_count" ) + 1 ) 
end 
setskin ( NOWINDOW ) 
game . open_mall ( ) 
